main: net.michal.blocker.WiksaBlocker
version: {project.version}
name: wiksa-blocker
description: basic command blocker for minecraft server with config
website: https://gihub.com/miszel-ini/wiksa-blocker